### ISSUE TITLE
After Upgrading API Level 30 camera not opening - Permission denied wrap code: 0xba709d37 

### ISSUE THREAD

**Issue by prabha303** [3DiVi/face-sdk#1]
Hi 

In Android, I have Upgraded Gradle target version 28 to 30. after that camera not opening, Permission denied wrap code: 0xba709d37

**face_recognition.sdk.SDKException: Permission denied wrap code: 0xba709d37.**

2020-09-11 17:52:27.426 4176-4344/ai.tranzo.ennik W/System.err: **com.vdt.face_recognition.sdk.SDKException: Permission denied wrap code: 0xba709d37.**
2020-09-11 17:52:27.426 4176-4344/ai.tranzo.ennik W/System.err:     at com.vdt.face_recognition.sdk.FacerecService.getLicenseState_jni(Native Method)
2020-09-11 17:52:27.427 4176-4344/ai.tranzo.ennik W/System.err:     at com.vdt.face_recognition.sdk.FacerecService.getLicenseState(FacerecService.java:943)
2020-09-11 17:52:27.427 4176-4344/ai.tranzo.ennik W/System.err:     at ai.tranzo.ennik.admin.Kiosk.FSDK_code.VidRecDemo.<init>(VidRecDemo.java:274)
2020-09-11 17:52:27.427 4176-4344/ai.tranzo.ennik W/System.err:     at ai.tranzo.ennik.admin.Kiosk.FSDK_code.MainActivity$LoadThread.run(MainActivity.java:434)

**Comment by ASinkov** [comment]
@prabha303, hello. 

Version 3.4 does not support api higher than 28 due to new restrictions in Android (it was indicated in the [comment](https://github.com/3DiVi/face-sdk/blob/v3.4.0/examples/android/demo/build.gradle#L15)). We released a new version of FaceSDK yesterday - v3.4.1, in which we added scoped storage and raised target SDK version in the example to 29.

**Comment by ASinkov** [comment]
@prabha303 did we solve your question?

**Comment by ASinkov** [comment]
This issue is to be closed due to long time now response. Please feel free to contact us again or reopen the issue if this issue persist.
